services:

  backend:
    build: ./backend
    ports:
      - 8082:8082
    networks:
      - foreign_key_nw
    command: ./build

  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    networks:
      - foreign_key_nw
    command: ["npm", "run", "dev"]
    depends_on:
     - backend

networks:
  foreign_key_nw: { }
