services:

  backend:
    build: ./backend
    env_file:
      - backend/config/prod.env
    ports:
      - 8082:8082
    networks:
      - foreign_key_nw
    command: ./build
    depends_on:
      - tg-bot

  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    networks:
      - foreign_key_nw
    command: ["npm", "run", "dev"]
    depends_on:
     - backend

  tg-bot:
    build: ./tg-bot
    env_file:
      - tg-bot/config/prod.env
    ports:
      - 8083:8083
    networks:
      - foreign_key_nw
    command: ./build

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl
    networks:
      - foreign_key_nw
    depends_on:
      - frontend

volumes:
  foreign_key_volume: {}

networks:
  foreign_key_nw: { }
