env: "local"
storage_path: "./storage"
storage_name: "storage.db"
images_path: "./images"
http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 60s
email:
  email_address: "foreignkey@bk.ru"
  password: "zHjSjnGzQWEmSJBnfWGg"
  smtp_host: "smtp.mail.ru"
  smtp_port: "25"
