basePath: /api
definitions:
  admin.GetProfileResponse:
    properties:
      error:
        type: string
      profile:
        $ref: '#/definitions/storage.Admin'
      status:
        type: string
    type: object
  admin.SignInRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  admin.SignUpRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  admin.TokenResponse:
    properties:
      error:
        type: string
      status:
        type: string
      token:
        type: string
    type: object
  admin.UpdateProfileRequest:
    properties:
      city:
        type: string
      father_name:
        type: string
      first_name:
        type: string
      image_id:
        type: integer
      last_name:
        type: string
    type: object
  cart.AddRequest:
    properties:
      count:
        type: integer
      product_id:
        type: integer
    type: object
  cart.ChangeCountRequest:
    properties:
      new_count:
        type: integer
      product_id:
        type: integer
    type: object
  cart.GetResponse:
    properties:
      cart_items:
        items:
          $ref: '#/definitions/storage.CartItem'
        type: array
      error:
        type: string
      status:
        type: string
    type: object
  customer.GetProfileResponse:
    properties:
      error:
        type: string
      profile:
        $ref: '#/definitions/storage.Customer'
      status:
        type: string
    type: object
  customer.GetResponse:
    properties:
      customers:
        items:
          $ref: '#/definitions/storage.Customer'
        type: array
      error:
        type: string
      status:
        type: string
    type: object
  customer.SignInRequest:
    properties:
      alias:
        type: string
      email:
        type: string
      password:
        type: string
    type: object
  customer.SignUpRequest:
    properties:
      alias:
        type: string
      email:
        type: string
      password:
        type: string
    type: object
  customer.TokenResponse:
    properties:
      error:
        type: string
      status:
        type: string
      token:
        type: string
    type: object
  customer.UpdateProfileRequest:
    properties:
      delivery_type:
        type: string
      father_name:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      payment_type:
        type: string
      phone:
        type: string
      telegram:
        type: string
    type: object
  image.UploadResponse:
    properties:
      error:
        type: string
      id:
        type: integer
      status:
        type: string
    type: object
  order.GetResponse:
    properties:
      error:
        type: string
      orders:
        items:
          $ref: '#/definitions/storage.Order'
        type: array
      status:
        type: string
    type: object
  order.UpdateStatusRequest:
    properties:
      order_id:
        type: integer
      status:
        type: integer
    type: object
  product.CreateRequest:
    properties:
      alias:
        type: string
      product_info:
        $ref: '#/definitions/product.Info'
    type: object
  product.GetResponse:
    properties:
      error:
        type: string
      products:
        items:
          $ref: '#/definitions/storage.ProductInfo'
        type: array
      status:
        type: string
    type: object
  product.Info:
    properties:
      description:
        type: string
      images_id:
        type: string
      name:
        type: string
      price:
        type: integer
    type: object
  product.UpdateActiveRequest:
    properties:
      active:
        type: integer
      alias:
        type: string
      product_id:
        type: integer
    type: object
  response.Response:
    properties:
      error:
        type: string
      status:
        type: string
    type: object
  storage.Admin:
    properties:
      city:
        type: string
      email:
        type: string
      father_name:
        type: string
      first_name:
        type: string
      id:
        type: integer
      image_id:
        type: integer
      last_name:
        type: string
    type: object
  storage.CartItem:
    properties:
      cart_id:
        type: integer
      count:
        type: integer
      id:
        type: integer
      product:
        $ref: '#/definitions/storage.ProductInfo'
    type: object
  storage.Customer:
    properties:
      delivery_type:
        type: string
      email:
        type: string
      father_name:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      payment_type:
        type: string
      phone:
        type: string
      telegram:
        type: string
      website_id:
        type: integer
    type: object
  storage.Order:
    properties:
      customer_id:
        type: integer
      date_time:
        type: string
      id:
        type: integer
      order_items:
        items:
          $ref: '#/definitions/storage.OrderItem'
        type: array
      status:
        type: integer
    type: object
  storage.OrderItem:
    properties:
      count:
        type: integer
      id:
        type: integer
      order_id:
        type: integer
      product:
        $ref: '#/definitions/storage.ProductInfo'
    type: object
  storage.ProductInfo:
    properties:
      active:
        type: integer
      description:
        type: string
      id:
        type: integer
      images_id:
        type: string
      name:
        type: string
      price:
        type: integer
      website_id:
        type: integer
    type: object
  website.AliasesResponse:
    properties:
      aliases:
        items:
          type: string
        type: array
      error:
        type: string
      status:
        type: string
    type: object
  website.CreateRequest:
    properties:
      alias:
        type: string
    type: object
  website.GetStyleResponse:
    properties:
      background_color:
        type: string
      error:
        type: string
      font:
        type: string
      status:
        type: string
    type: object
  website.StyleRequest:
    properties:
      alias:
        type: string
      background_color:
        type: string
      font:
        type: string
    type: object
host: localhost:8082
info:
  contact: {}
  title: ForeignKey
  version: "1.0"
paths:
  /admin/get-profile:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/admin.GetProfileResponse'
      security:
      - ApiKeyAuth: []
      summary: Get admin profile
      tags:
      - admin
  /admin/sign-in:
    post:
      consumes:
      - application/json
      parameters:
      - description: sign in
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/admin.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/admin.TokenResponse'
      summary: SingIn admin
      tags:
      - admin
  /admin/sign-up:
    post:
      consumes:
      - application/json
      parameters:
      - description: sign up
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/admin.SignUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/admin.TokenResponse'
      summary: SingUp admin
      tags:
      - admin
  /admin/update-profile:
    put:
      consumes:
      - application/json
      parameters:
      - description: new profile data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/admin.UpdateProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: Update admin profile
      tags:
      - admin
  /cart/add:
    post:
      consumes:
      - application/json
      description: Добавляет товар в корзину, если товар уже в корзине, увеличивает
        количество
      parameters:
      - description: product id and count
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/cart.AddRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: Create cart item
      tags:
      - cart
  /cart/change-count:
    patch:
      consumes:
      - application/json
      description: Изменяет кол-во товара в корзине на new_count
      parameters:
      - description: product id and count
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/cart.ChangeCountRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: Change count curt item
      tags:
      - cart
  /cart/get:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/cart.GetResponse'
      security:
      - ApiKeyAuth: []
      summary: Get all cart items
      tags:
      - cart
  /customer/get-by-alias/{alias}:
    get:
      parameters:
      - description: website alias
        in: path
        name: alias
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/customer.GetResponse'
      security:
      - ApiKeyAuth: []
      summary: Get all customers by alias
      tags:
      - customer
  /customer/get-profile:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/customer.GetProfileResponse'
      security:
      - ApiKeyAuth: []
      summary: Get customer profile
      tags:
      - customer
  /customer/sign-in:
    post:
      consumes:
      - application/json
      parameters:
      - description: sign in
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/customer.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/customer.TokenResponse'
      summary: SingIn customer
      tags:
      - customer
  /customer/sign-up:
    post:
      consumes:
      - application/json
      parameters:
      - description: sign up
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/customer.SignUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/customer.TokenResponse'
      summary: SingUp customer
      tags:
      - customer
  /customer/update-profile:
    put:
      consumes:
      - application/json
      parameters:
      - description: new profile data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/customer.UpdateProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: Update customer profile
      tags:
      - customer
  /image/download/{id}:
    get:
      description: При удачном запросе вернет картинку в body со статусом 200, при
        неудачном json с ошибкой
      parameters:
      - description: image id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - image/jpeg
      - image/png
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
      summary: DownloadImage
      tags:
      - files
  /image/upload:
    post:
      consumes:
      - image/jpeg
      - image/png
      description: В боди должна быть картинка в виде массива байт
      parameters:
      - description: byte image
        in: body
        name: input
        required: true
        schema:
          items:
            type: integer
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/image.UploadResponse'
      summary: UploadImage
      tags:
      - files
  /order/get:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/order.GetResponse'
      security:
      - ApiKeyAuth: []
      summary: Get all orders
      tags:
      - order
  /order/get-by-alias/{alias}:
    get:
      parameters:
      - description: website alias
        in: path
        name: alias
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/order.GetResponse'
      security:
      - ApiKeyAuth: []
      summary: Get all orders by alias
      tags:
      - order
  /order/get-completed/{alias}:
    get:
      parameters:
      - description: website alias
        in: path
        name: alias
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/order.GetResponse'
      security:
      - ApiKeyAuth: []
      summary: Get completed orders by alias
      tags:
      - order
  /order/make:
    post:
      description: Создает заказ исходя из корзины покупателя
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: Make order
      tags:
      - order
  /order/set-status:
    patch:
      consumes:
      - application/json
      parameters:
      - description: style to website
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/order.UpdateStatusRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: Change order status
      tags:
      - order
  /product/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: product info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/product.CreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: Create product
      tags:
      - product
  /product/get-all-by-alias/{alias}:
    get:
      description: Возвращает ВСЕ ТОВАРЫ сайта по алиасу, только для админа
      parameters:
      - description: website alias
        in: path
        name: alias
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/product.GetResponse'
      security:
      - ApiKeyAuth: []
      summary: GetAllByAlias
      tags:
      - product
  /product/get-by-alias/{alias}:
    get:
      description: Возвращает ТОЛЬКО АКТИВНЫЕ товары сайта по алиасу
      parameters:
      - description: website alias
        in: path
        name: alias
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/product.GetResponse'
      summary: GetByAlias
      tags:
      - product
  /product/set-active:
    patch:
      consumes:
      - application/json
      parameters:
      - description: active status
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/product.UpdateActiveRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: Change product active status
      tags:
      - product
  /website/aliases:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/website.AliasesResponse'
      security:
      - ApiKeyAuth: []
      summary: Get all users aliases
      tags:
      - website
  /website/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: alias new website
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/website.CreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: Create website
      tags:
      - website
  /website/delete/{alias}:
    delete:
      description: Удаляет сайт по алиасу
      parameters:
      - description: website alias
        in: path
        name: alias
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: Delete website
      tags:
      - website
  /website/get-style/{alias}:
    get:
      parameters:
      - description: website alias
        in: path
        name: alias
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/website.GetStyleResponse'
      summary: Get website style
      tags:
      - website
  /website/set-style:
    patch:
      consumes:
      - application/json
      parameters:
      - description: style to website
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/website.StyleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: Change style
      tags:
      - website
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
